### ISSUE TITLE
How to handle errors when uuid metadata is not found?

### ISSUE THREAD

**Issue by shazanfar** [christinehou11/HuBMAPR#11]
Hi Christine,

I've tried again exploring with the first of the raw seqFish data, and find that there is a cryptic error when the uuid is not associated with the category of interest (I think), a case below. In this situation is it worthwhile including a call to `uuid_provenance` within `donor_metadata` function to extract the relevant UUID, or perhaps just return a more informative error.

As an aside, I am getting quite confused with many different UUIDs, it's not immediately obvious to me which category a UUID might belong to... would it be worthwhile to create a function like `uuid_type` or similar? I suppose `uuid_provenance` gets quite close, but I notice that in the example below for the donor UUID the output of `uuid_provenance` is `list()`.

Thanks again for your hard work on this!

```
library(HuBMAPR)
library(dplyr)

uuid = datasets() |> 
  filter(dataset_processing_category == "Raw" & dataset_type == "seqFish") |> 
  pull("uuid") |> 
  head(1)

uuid
# returns below
# "bf447e198a99cb780d93437f05b2452d"

dataset_metadata(uuid)

sample_metadata(uuid)

# this returns an error
donor_metadata(uuid)
# Error in `unnest()`:
# ! In row 1, can't recycle input of size 0 to size 34.
# Run `rlang::last_trace()` to see where the error occurred.

# one would need to first run below, and see what is the donor uuid
uuid_provenance(uuid)

donor_metadata("a9175b3b41ef3cb88afa0cb1fff0f4e7")
```

**Comment by christinehou11** [comment]
Hi! Thanks for the message.

1. The `uuid` you pull out is from the function `dataset()`, Therefore, the `uuid` category must belong to the dataset entity category, which you may need to use the corresponding `dataset_*()` function to retrieve dataset metadata.  The' uuid' category matches the specific function you use to retrieve related information. If you are using `uuid` from donor entity type, you can use `donor_metadata()` to retrieve the metadata information.
2. You use the `uuid_provenance()` function to retrieve the list of donors or samples from which the dataset comes. The donor will be the top one in the provenance hierarchy, and there won't be anyone before the donor. That's why the returned result is `list()`.

Hope this comment help!
