### ISSUE TITLE
a few comments / suggestions for the `datasets()` function

### ISSUE THREAD

**Issue by stephaniehicks** [christinehou11/HuBMAPR#12]
Thank you @christinehou11 for this great package! One question I had was if we could make the names of the columns uniform? For example, I noted we have `dataset_type` (it does not end in an s) and `data_types` (it does end in an s). I would assume to make it consistent with other names, it should not have an s. What do you think? 

```
> datasets()
# A tibble: 3,301 × 14
   uuid    hubmap_id dataset_type data_types organ analyte_class sample_category
   <chr>   <chr>     <chr>        <chr>      <chr> <chr>         <chr>          
 1 319579… HBM965.G… RNAseq       sciRNAseq  Heart RNA           block          
 2 756a0e… HBM388.Z… RNAseq       sciRNAseq  Heart RNA           block          
 3 7e4c58… HBM952.D… ATACseq      sciATACseq Heart DNA           block          
 4 e75d8b… HBM667.Z… RNAseq       sciRNAseq  Heart RNA           block          
 5 42b73e… HBM972.V… RNAseq       sciRNAseq  Heart RNA           block          
 6 48da18… HBM583.S… ATACseq      sciATACseq Sple… DNA           block          
 7 fe43e2… HBM389.N… ATACseq      sciATACseq Smal… DNA           block          
 8 02dcd8… HBM429.Q… ATACseq      sciATACseq Smal… DNA           block          
 9 dd39ed… HBM278.G… ATACseq      sciATACseq Heart DNA           block          
10 8ea82d… HBM445.L… ATACseq      sciATACseq Panc… DNA           block          
# ℹ 3,291 more rows
# ℹ 7 more variables: status <chr>, dataset_processing_category <chr>,
#   pipeline <chr>, registered_by <chr>, donor.hubmap_id <chr>,
#   group_name <chr>, last_modified_timestamp <chr>
# ℹ Use `print(n = ...)` to see more rows
```

Other things I noticed. 

- In the `sample_category` column in `datasets()`, there are things like `block`, but there are also things such as `block, block, block, block` (or `section` and ` section, section, section, section, section`). Can you clarify where this information comes from? is it psosible to clean that up? 
- In the `donor.hubmap_id` column in `datasets()`, I see there is a dot instead of an underscore. Can we change it to underscores to make the columns uniform?

**Comment by christinehou11** [comment]
Thanks for the comment!

I think I need to add more textual descriptions on the column names. I think `dataset_type` and `data_types` show different information about the dataset category. For example,
` datasets |>
+     filter(uuid == "232aac63e35e0fd4a856bb2ebf7f8d50") |>
+     select(dataset_type, data_types)
# A tibble: 1 × 2
  dataset_type data_types
  <chr>        <chr>     
1 RNAseq       sciRNAseq`

It means  that the "232aac63e35e0fd4a856bb2ebf7f8d50" dataset belongs to `RNAseq`, but more specifically belongs to `sciRNAseq`. 
The `dataset_type` is the complete data, and there is no empty entry because it basically displays the general assay type. But `data_type` gives an additional assay type information, which can be helpful for user to have a further filter.

I can add more textual descriptions about the `sample category` because it is related to the hierarchy provenance of a specific dataset or sample. The picture under Entity API from [here](https://docs.hubmapconsortium.org/apis.html) can be helpful.

I agree with renaming `donor.hubmap_id`. I will edit the column name later.

Hope the comment helps!

**Comment by christinehou11** [comment]
Done!
